version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  hazelcast:
    image: hazelcast/hazelcast
    ports:
      - 5701:5701
    environment:
      HZ_NETWORK_PUBLICADDRESS: 127.0.0.1:5701
